[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.1.5"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
tar = "0.4.44"
